name: win_toast_example
description: Demonstrates how to use the win_toast plugin.

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  win_toast:
    path: ../
  cupertino_icons: ^1.0.2
  xml: ^7.0.1
  mixin_logger: ^0.2.0
  path_provider: ^2.0.11
  path: ^1.8.0

  material_ui: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.8

flutter:
  uses-material-design: true
  assets:
    - assets/image.png

msix_config:
  display_name: WinToastExample
  identity_name: one.mixin.WinToastExample
  toast_activator:
    clsid: "936C39FC-6BBC-4A57-B8F8-7C627E401B2F"
    arguments: "-ToastActivated"
    display_name: "Example Application"
  msix_version: 1.0.4.0